version: 2.1
orbs:
  node: circleci/node@5.1.0

executors:
  my-exe:
    docker:
      - image: cimg/node:19.8.0
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD


jobs:
  cicd-job:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: install dependencies - NPM packages
          command: npm install
      - run:
          name: run tests
          command: npm run test
      - run:
          name: run linter
          command: npm run lint
#
#      - run:
#          name: CD-deploy the service
#          command: curl "https://api.render.com/deploy/srv-cgkkr10rddleudv4ss30?key=Kq-olmuo8DE"


workflows:
  my-workflow:
    jobs:
      - test
